---
language: python
python: "3.6"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  - pip install -r teamserver/requirements.txt
  - pip install ansible-lint

script:
  - python teamserver/teamserver.py &
  - curl http://127.0.0.1:5000/status | grep "200"
