---
language: python
python: "3.6"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install requirements
  - pip install -r teamserver/requirements.txt

before_script:
  # Start test teamserver
  - python teamserver/teamserver.py &

script:
  # Check teamserver status
  - curl http://127.0.0.1:5000/status | grep "200"

