---
language: python
python: "3.6"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install requirements
  - sudo apt-get install pylint
  - pip install -r teamserver/requirements/dev.txt

before_script:
  # Ensure program passes lint tests
    - find teamserver/ -name "*.py" -exec pylint --output-format=text --reports=y --disable=fixme --disable=trailing-newlines --disable=invalid-name --disable=wrong-import-position '{}' +

script:
  # Run all unit tests
  - python -m unittest discover -s teamserver/tests -p '*_test.py'

