---
language: python
python: "3.6"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install python dependancies
  - pip install -r teamserver/requirements/dev.txt
before_script:
  # Display pylint version
  - pylint --version
  # Ensure program passes lint tests
  - find teamserver/ -name "*.py" -exec pylint --output-format=text --reports=y '{}' +

script:
  # Run all unit tests
  - cd teamserver; python run_tests.py

