---
language: python
python: "3.6"

before_install:
  # Make sure everything's up to date.
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - sudo apt-get update -qq

install:
  # Install mongodb
  - sudo apt-get install -y mongodb-org
  # Install python dependancies
  - pip install -r teamserver/requirements/dev.txt
before_script:
  # Display pylint version
  - pylint --version
  # Ensure program passes lint tests
  - find teamserver/ -name "*.py" -exec pylint --output-format=text --reports=y '{}' +

script:
  # Run all unit tests
  - python -m unittest discover -s teamserver/tests -p '*_test.py'

