version: '3'

services:
  teamserver:
    build: teamserver/
    ports:
      - "80:80"
    environment:
      - CELERY_BROKER_URL=amqp://arsenal-rabbitmq:5672
      - CELERY_RESULT_BACKEND=amqp://arsenal-rabbitmq:5672
      - DB_NAME=arsenal_sample
      - DB_HOST=arsenal-mongo
      - DB_PORT=27017
      - API_KEY_SALT=thebestsaltthebestsalt

  redis:
    image: redis

  mongo:
    image: mongo

  rabbitmq:
    image: rabbitmq
