version: '3'

services:
  teamserver:
    build: teamserver/
    ports:
      - "80:80"
    environment:
      - CELERY_BROKER_URL=amqp://arsenal_rabbitmq_1:5672
      - CELERY_RESULT_BACKEND=amqp://arsenal_rabbitmq_1:5672
      - DB_NAME=arsenal_sample
      - DB_HOST=arsenal_mongo_1
      - DB_PORT=27017
      - SLACK_API_TOKEN=None

  redis:
    image: redis

  mongo:
    image: mongo

  rabbitmq:
    image: rabbitmq
